notebook_base_path: /assets/notebooks/

baseurl: /dsm-portfolio-site

include:
- _pages

plugins:
- jekyll-remote-theme
- jekyll-data
- jekyll-jupyter-notebook

theme: dsm-portfolio-theme
remote_theme: joshhills/dsm-portfolio-theme